spring.application.name=ThymeleafTutoriaTwo

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/thymeleaftutorialtwo}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:S*1student2}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080